trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    docker run -t yugabyteci/yb_build_infra_centos7:v2020-12-14T01_12_21 \
    bash -c "
       curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --quiet --no-modify-path -y
       ~/.cargo/bin/cargo install sccache
    "
  displayName: 'Build and package sccache'
